services:
  example-emails-batch:
    container_name: ${COMPOSE_PROJECT_NAME}_example-emails-batch
    build:
      target: development
      dockerfile: ./docker/app/php-fpm/Dockerfile
      additional_contexts:
        php-fpm-ctx: ./docker/app/php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
    env_file:
      - ./src/.env
    environment:
      CONTAINER_ROLE: batch
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
        consistency: cached
    depends_on:
      db:
        condition: service_healthy
    command: [ "php", "artisan", "mail:send" ]
    networks:
      - common
